const hodnoceni = [
  [
    {
      name: "Spontánní aktivisté (hybatelé)",
      desc:
        "Obecně patříte k těm lidem, kteří se sice neobávají rizik stáří, ale zároveň se na své budoucí stáří připravují spontánně a v různých oblastech života Váš přístup k životu funguje jako prevence vůči rizikům stáří. To znamená, že s riziky stáří bojujete jen jaksi mimochodem, protože máte odpor k rizikům jako takovým. Riskování je pro vás obecně nežádoucí chováním, a proto ve svém každodenním životě standardně uplatňujete zásadu předběžné opatrnosti. Přístup spontánního aktivisty k přípravě na stáří je typický pro 27 % dospělých obyvatel ČR ve Vašem věku.",
      recom:
        "Ano, ještě máte hodně času na stáří a během „čekání“ na něj se může leccos stát, a to jak v pozitivním tak negativním smyslu. Nicméně pokud budete dělat to, co děláte doposud a v dalších letech přidáte cílenější aktivitu či aktivity, velmi zvyšujete své šance na dobře prožívané a důstojné stáří. Co byste mohla/a dělat právě nyní? Aktuálně se můžete soustředit třeba na mezigenerační solidaritu a komunikaci. Komunikace i pomoc či lépe podpora starším blízkým z vaší rodiny (babičky, dědečkové, tety i strýcové….) případně i neznámým lidem formou dobrovolnické činnosti, může vést k získání zajímavých a podstatných životních zkušeností. I tímto bohulibým způsobem můžete zvýšit svou připravenost na něco tak vzdáleného, jako je život ve stáří. Spousta lidí kolem vás sice řekne, že v životě se nelze na nic připravit předem a že je třeba čekat, až se to stane vám, ale právě třeba mezigenerační aktivita může být už právě vaší osobní přípravou…",
    },
    {
        name: "Odevzdaní trpitelé",
        desc: "Při svém mládí vnímáte rizika stáří vcelku intenzivně. Nemáte ve svém okolí někoho blízkého, u koho se právě tato rizika změnila v reálný stav, a i proto vás myšlenky na stárnutí trochu „děsí“? Ale aktuálně nemáte dost schopností ani prostředků a možná ani motivaci abyste mohli rozvíjet nějaké strategie nebo alespoň jednotlivé činnosti, které by vám (po)mohly přiblížit spokojené stáří. Je to jen proto, že vaše stáří je opravdu nekonečně daleko? Nebo z nějakého jiného důvodu? Zatím se tedy zdá, že rizika stáří podstupujete nedobrovolně, a že nezbývá nic jiného než doufat, že stát se o vás postará. Své úsilí věnujete hlavně překonávání překážek aktuálního života. Snášení rizik stáří je pro vás alternativou k velmi pravděpodobným ztrátám, ke kterým by jinak došlo, kdybyste všechny zdroje nemohli použít na své dnešní nezbytné životní výdaje. Přestože se stáří obáváte, aktivně žijete hlavně pro dnešek. Přístup odevzdaného trpitele k přípravě na stáří je typický pro 15 % dospělých obyvatel ČR ve vašem věku. V rámci své věkové skupiny patříte k typu, který je nejméně častý.",
        recom: "Ve Vaší generaci, jste celkem výjimeční v tom, jací jste z hlediska vnímání stáří. Nejsme si ale jistí, že je to dlouhodobě udržitelný postoj. I když se stáří nebo jeho rizik obáváte, neznamená to, že s nimi nemůžete vůbec nic dělat právě teď. Samozřejmě nemyslíme si, že celé dny trávíte svázaní pocity strachu ze stáří, protože téma pro vás pravděpodobně není úplně vepředu žebříčku starostí. Kdybyste třeba někdy měli čas, zkuste se obrátit na někoho, komu věříte a pobavit se s ním o vašich vyhlídkách na stáří. Dokonce můžete vyhledat i profesionála – mentora, poradce (online i offline), záleží na vašich preferencích. Hlavní je se nebát. A samozřejmě pokud žijete v dobrém rodinném zázemí, mluvte o tom se svými blízkými. Pokud jde konkrétně o rodiče, jaké mají oni obavy a co s nimi dělají? Nejde ale jen o tom mluvit, ale zkusit něco málo i udělat, třeba si odkládat maličko peněz stranou, začít běhat či cvičit nebo se častěji scházet s přáteli a budovat si vlastní okruh blízkých lidí, na něž se můžete spolehnout, protože ve stáří se jejich důležitost citelně zvyšuje.",
    },
    {
        name: "Bezstarostní jezdci",
        desc: "Rizika stáří se vám zdají příliš mlhavá a asi vzdálená, abyste se jimi zabývali. Nesnažíte se proti nim tudíž zajišťovat. Nechcete se zatěžovat řešením problémů, které jsou příliš daleko a ponecháváte věci tak, jak samy běží. Obecně ale platí, že jste spíše fatalisti: vše už je napsáno v knize vašeho osudu a na tom svým úsilím už nic moc nelze změnit. Jste tak dobrovolnými nositeli rizik stáří (a možná nejen jeho), a spoléháte, že to s vámi pod ochranným deštníkem systému státní péče nějak dopadne. Věříte, že budete mít třeba štěstí a váš život ve stáří nepřekročí hranice katastrofy. Přístup bezstarostného jezdce k přípravě na stáří je typický pro 34 % dospělých obyvatel ČR ve vašem věku. Patříte do skupiny, která je z hlediska přípravy na stáří, největší.",
        recom: "Je samozřejmě otázka, zdali popsaný přístup ke stáří (a jeho vzdálené perspektivě) ještě během svého „dospívání“ radikálně nezměníte. Užívat si života naplno právě teď je hodnota důležitá pro lidi napříč věkovými skupinami. Jste si ale vědomí toho, že tímto způsobem se poštěstí zestárnout ve zdraví jen málokomu?  Asi o následcích svého hédonistického přístupu k životu moc nepřemýšlíte. Ty sice nemusí být vidět hned, ale zároveň se s nimi můžete setkat i mnohem dříve než ve stáří. Nechcete s tím něco udělat? Pokud nežijete jako vzor zdravého životního stylu, nešlo by svoje neřesti alespoň částečně eliminovat? Ne všechno najednou, ale třeba jen jednu. Pro teď. Pokud utrácíte bez rezerv, zkuste to jinak. Jak dlouho vám přináší radost/potěšení nová věc nebo zážitek? Zkuste si něco málo odepřít, třeba jen na omezenou dobu a uvidíte, co to s vámi udělá. Ano, času máte dost, ale co zkusit udělat něco hned a být za sebe alespoň částečně zodpovědný.",
    },
    {
        name: "Ostražití hlídači",
        desc: "Je pro vás charakteristická vysoká míra vnímavosti vůči rizikům stáří: nejen, že je vidíte, ale také jsou pro vás zdrojem obav. A proto se s tím snažíte něco dělat: máte vlastní, celkem bohatě rozvinutou strategií zabezpečování na stáří. Rizika stáří berete jako životní výzvu. Vidíte v nich reálnou hrozbu, kterou je potřeba ostražitě hlídat a mít ji pod kontrolou. Kalkulujete s možnými ztrátami a náklady. Jste přesvědčení, že aktivní příprava na rizika života ve stáří již teď se vyplatí a ve vašem případě se může s přibývajícím věkem příprava ještě zintenzivnit. Snažíte se tato rizika snižovat, co to jen jde, abyste měli větší jistotu prožití naplněného stáří. Přístup ostražitého hlídače k přípravě na stáří je typický pro 24 % dospělých obyvatel ČR ve vašem věku, což je docela velký podíl uvážíme-li, jak vzdálené stáří pro vás je.",
        recom: "Je moc dobře, že přemýšlíte o svém životě v dlouhodobém výhledu. A je dobře, že si uvědomujete rizika spojená se stárnutím. A úplně nejlepší je, že s tím něco vědomě děláte. Obojí je pro vaši generaci ne úplně typické a určitě sám/sama víte, že stereotypy o mladých s takovou eventualitou ani nepočítají a přičítají vám hlavně mladickou lehkovážnost…. Možná jste takoví, protože máte dobrý příklad ze svého okolí.  Možná máte rodiče, kteří vám už od dětství platili důchodové připojištění, nebo berete rady svých starších členů rodiny vážně a nepouštíte je jedním uchem dovnitř a druhým ven. Nebo jste prostě „přirozeně“ zodpovědní. Těžko vám můžeme radit, abyste dělali něco víc. Máme ale jednu otázku k zamyšlení: Berete život spíše jako dar, se vším všudy i se stářím? Pokud ano, doufáme, že ho prožíváte bez přílišného stresu, a to nejen ze stárnutí. Ostražitost vůči rizikům stáří by vám neměla bránit ve šťastném prožívání vašeho mládí.",
    }
  ],
  [
    {
      name: "Spontánní aktivisté (hybatelé)",
      desc: "Gratulujeme! Váš finanční i sociální kapitál, spektrum Vašich aktivit a Vaše životní úspěchy Vás zatím chrání proti rizikům stáří. Patříte k těm lidem, kteří se sice příliš neobávají rizik stáří, ale zároveň vaše spontánní životní aktivity celkem spolehlivě fungují jako prevence vůči rizikům stáří. To znamená, že s riziky stáří bojujete jen jaksi mimochodem, protože Vaše strategie je spíše obecná, nikoli konkrétně zacílená na rizika stáří. Ve svém každodenním životě standardně uplatňujete zásadu předběžné opatrnosti, takže kdykoli riskujete – třeba při investování, můžete se spolehnout na solidní zajištění v jiných oblastech. Přístup spontánního aktivisty k přípravě na stáří je typický pro 24 % dospělých obyvatel ČR ve vašem věku.",
      recom:
        "Třebaže máte rizika více méně dobře rozložená a pod kontrolou, je dobré počítat s tím, že rizika stárnutí mají svá specifika, která je dobré při Vašem dalším rozhodování zohlednit. Komunikujte se staršími generacemi o jejich očekáváních a potřebách, abyste si sami utříbili svou vlastní představu stárnutí. Je možné, že existují kroky a opatření, které jste dosud nevnímali jako důležité, ale při pohledu do budoucna a v delší perspektivě se mohou projevit jako klíčové pro dosažení Vašeho ideálu. Začněte uvažovat o přeskupení Vašich rodinných aktiv a statků s výhledem na několik desetiletí dopředu. Uspořádání, které se Vám zdá v současnosti jako optimální, nemusí být optimální v horizontu deseti patnácti let. Pokuste si vytyčit cíle, kterých chcete do svého stáří a během něho dosáhnout a naplánovat si alespoň v hrubých obrysech, co všechno pro to budete potřebovat. Začněte se zajímat o to, jak fungují různé zdravotnické a sociální služby pro seniory. Nejen vzhledem k vaší budoucí situaci, ale především v mnohem aktuálnější souvislosti s vašimi blízkými, kteří se dostávají do životní etapy křehkého stáří anebo už v něm jsou. I tuhle zkušenost můžete využit pro sebe. ",
    },
    {
        name: "Odevzdaní trpitelé",
        desc: "Patříte mezi ty, kteří sice vnímají rizika stáří vcelku intenzivně, ale nemají dost schopností a prostředků případně motivace, aby mohli vyvíjet komplexnější strategie, které by Vám mohly zaručit spokojené stáří. Rizika stáří podstupujete nedobrovolně, strádáte ekonomicky, zdravotně i/nebo sociálně a zdá se, že Vám nezbývá nic jiného než doufat, že stát se o Vás postará. Snášení rizik stáří je pro vás alternativou k velmi pravděpodobným ztrátám, ke kterým by jinak došlo, kdybyste všechny zdroje nemohli použít na své dnešní nezbytné životní výdaje. Žijete tedy hlavně dneškem, protože dělat něco pro budoucnost je pro vás nyní příliš složité. Ve vaší skupině je odevzdaných trpitelů 18 %.",
        recom: "Život se s Vámi nemazlí a ani vyhlídky na stáří zatím nejsou nejrůžovější. Není však všem dnům konec. Nepropadejte zádumčivosti – jste dosud ve věku, kdy se dá leccos změnit a obrátit k lepšímu. Klíčové je, že si rizika stáří uvědomujete a chcete s nimi něco dělat. Změny si totiž vyžádají určitou iniciativu z Vaší strany. Uvažujte, na jakých pilířích, třebaže se zatím zdají vratké, můžete do budoucna stavět. Vezměte do úvahy svou finanční situaci, zdravotní stav a síť Vašich známých či přátel. Pokud se nacházíte v tíživé ekonomické situaci, zkuste provést revizi svých možností. Existuje možnost získat lépe placenou práci nebo výhodnější bydlení ve Vašem okolí nebo třeba v jiném regionu? Nejsou ve Vašich výdajích položky, které by se daly vypustit nebo odložit na později? Máte možnost část svého volného času věnovat péči o své zdraví nebo třeba sportu? Je někdo ve Vašem okolí, na koho se můžete spolehnout a kdo to s Vámi myslí dobře? Pokud ne, jistě máte možnost část svého volného času strávit ve společnosti lidí, kteří mají rádi podobné aktivity, jako vy. Vybudovat síť přátel, se kterými budete sdílet své starosti, nemusí být ani drahé ani vyčerpávající a přátelé z mládí ve stáří jako když najdeš. Nejlepší a nejvěrnější oporu ovšem obvykle naleznete ve své rodině. Proto byste měli věnovat zvýšenou pozornost rodinným vztahům a vazbám, které Vás v nejtěžších momentech podrží. V případě, že rodinu nemáte, nebo se s rodinou z nějakého důvodu nestýkáte, stále máte příležitost založit si rodinu vlastní. Děti vždy přináší naději a nejen z našeho výzkumu vyplývá, že právě děti budou hrát ve Vašem stáří klíčovou a jen těžko nahraditelnou úlohu. Pokud cítíte, že svou situaci nezvládáte, existuje řada organizací – státních i neziskových, na které se můžete obrátit o pomoc. Nejsou to sexy rady, ale můžou fungovat.",
    },
    {
        name: "Bezstarostní jezdci",
        desc: "Rizika stáří se vám zdají příliš mlhavá a asi vzdálená, abyste se jimi zabývali. Nesnažíte se proti nim tudíž zajišťovat. Nechcete se zatěžovat řešením problémů, které jsou daleko a ponecháváte věci tak, jak samy běží. Obecně ale platí, že jste spíše fatalisti: vše už je napsáno v knize vašeho osudu a na tom svým úsilím už nic nelze změnit. Jste dobrovolnými nositeli rizik stáří, a spoléháte, že to s vámi pod ochranným deštníkem systému státní péče nějak dopadne. Věříte, že budete mít třeba štěstí a váš život ve stáří nepřekročí hranice katastrofy. Přístup bezstarostného jezdce k přípravě na stáří je typický pro 30 % dospělých obyvatel ČR ve vašem věku. Patříte do skupiny, která je z hlediska přípravy na stáří, největší. Je samozřejmě otázka, zdali popsaný přístup ke stáří (vzdálené perspektivě) ještě radikálně nezměníte. Je nejvyšší čas.",
        recom: "Žijete zatím ve sladkém nevědomí.  Váš přístup by se dal popsat jako „však to nějak dopadne“. Jistě, dopadne to. S trochou nadsázky lze Vaši strategii přirovnat ke skoku z letadla bez padáku. Zažijete možná neskutečný pocit volnosti a maximální vzrušení a není vyloučeno, že Vás jako v akčním filmu na poslední chvíli někdo zachytí a vy dopadnete do měkkého. Na druhou stranu se nesmíte divit, pokud dopadnete velmi tvrdě. S přibývajícím věkem totiž počet záchytných možností i zachránců klesá. Ač o tom možná nevíte, vystavujete se riziku neuspokojivého stáří a dost možná i zbytečné předčasné smrti. Dobrá zpráva je, že stále máte čas věci změnit. Začněte tím, že si promluvíte s lidmi ze svého nejbližšího okolí. Zeptejte se rodičů nebo prarodičů, jak se jim žije, a zda by si bývali nechtěli některé věci zařídit jinak. Přemýšlejte o tom, zda byste chtěli prožít stáří podobně jako oni: jak vypadá váš „ideál“?  A co pro něj můžete udělat. Své stávající vztahy s přáteli a se členy rodiny se pokuste maximálně upevnit. Pokud ještě nemáte děti, zamyslete se, zda je skutečně ve stáří nebudete „potřebovat“. Z našeho i dalších průzkumů vyplývá, že role dětí bývá při zajišťování uspokojivého stáří rodičů jen těžko zastupitelná. Pokud děti nemůžete nebo nechcete mít, zaměřte se na budování jiných silných sociálních vztahů. V případě, že Vám tyto v budoucnu budou chybět, bude pro Vás zajištění slušného standardu stáří drahé. Musíte tedy své úsilí opřít do vydělávání většího objemu peněz. Cílem je ušetřit pokud možno čtvrtinu příjmů na investice. Samotný vyšší příjem v současnosti Vám totiž nemusí zaručovat i dostatečný příjem ve stáří ve formě státní penze. Můžete začít konzervativně: např. státem podporovaným důchodových připojištěním. Odvážnější investicí může být nákup nemovitostí, nebo dluhopisy, kde lze předpokládat slušné zhodnocení. Můžete investovat po menších částkách a nezapomenout ověřit si důvěryhodnost subjektu, jenž daný produkt nabízí. Ve Vašem věku si ještě můžete dovolit investovat i do krátkodobě rizikovějších instrumentů, které ovšem mohou mít v delším výhledu vyšší výnos. V neposlední řadě nepřeceňujte možnosti vašeho těla odolávat různým zátěžím. Vyvarujte se především závislostem na alkoholu a kouření. Investicí, kterou Vám nikdo nevezme, jsou peníze vložené do kvalitního jídla s vyváženým obsahem živin a vitamínů a zdravého pohybu. Proč neinvestovat pár stokorun třeba do permanentky do bazénu?",
    },
    {
        name: "Ostražití hlídači",
        desc: "Patříte mezi lidi, pro které je charakteristická vysoká míra vnímavosti vůči rizikům stáří a zároveň se také vyznačujete intenzivní a relativně komplexní strategií zabezpečování na stáří. Rizika stáří berete jako životní výzvu. Vidíte v nich reálnou hrozbu, kterou je potřeba ostražitě hlídat a mít ji pod kontrolou. Jako hlídači kalkulujete s možnými ztrátami a náklady. Jste přesvědčení, že aktivní příprava na rizika života ve stáří již teď se vyplatí a ve vašem případě se může s přibývajícím věkem příprava ještě zintenzivnit. Snažíte se tato rizika snižovat, co to jen jde, abyste měli větší jistotu prožití naplněného stáří. Přístup ostražitého hlídače k přípravě na stáří je typický pro 27 % dospělých obyvatel ČR ve vašem věku.",
        recom: "Jen tak dál! Dobře víte, že rizika stárnutí se nesmí podceňovat. Na druhou stranu strach ze stáří by Vás neměl zcela svazovat a být zdrojem přehnaného stresu či nervozity. Rozhodně by neměl zabránit v tom, abyste si dostatečně užili výhod, které přináší Váš stávající věk, případně abyste dokázali čelit jiným akutnějším druhům rizik. Neměli byste především přehlížet aktuální a střednědobé potřeby Vaší rodiny, zejména dětí. V relativně blízké době nejspíš budete čelit problémům spojených se stárnutím generace Vašich rodičů a prarodičů, kteří se budou posouvat do zranitelnějších věkových kategorií. Je velmi důležité, abyste s nimi navázali otevřenou komunikaci o jejich představách a ideálech spojených se stářím. Jistě je moudré v dostatečném předstihu koordinovat rozhodnutí týkající se rodinného majetku a hodnot. Neměli byste se vyhýbat ani jinak citlivým otázkám spojených se smrtí svých blízkých a vypořádáním všech souvisejících záležitostí. Péče o starší generace a další úkony mohou časem přecházet na Vás, a to je vynikající příležitost dát příklad generaci vašich dětí, jak mají postupovat, až se do etapy křehkého stáří dostanete vy, jejich rodiče."
    }
  ],
  [
    {
      name: "Spontánní aktivisté (hybatelé)",
      desc: "Patříte k těm lidem, kteří se sice příliš neobávají rizik stáří, ale zároveň váš spontánní životní aktivismus celkem spolehlivě funguje jako prevence vůči rizikům stáří. To znamená, že s riziky stáří bojujete jaksi mimochodem, protože Vaše strategie je spíše obecná, nikoli konkrétně zacílená na stáří. Rizika stáří se vám jeví jako nepříliš velká, protože máte pocit, že jsou pod vaší kontrolou a že svůj život držíte pevně v rukou. Býváte dobře materiálně zabezpečení a důvěřujete nejen sobě, ale také statním institucím. Dohromady tvoříte asi 20% populace ve vašem věku (46-59).",
      recom:
        "Ve svém životě jste aktivní, a jen tak dále! Přechod do důchodu, který vás za čas čeká, by neměl znamenat, že nebudete stejně aktivní, jak jste teď. Pokud máte pocit, že finanční zabezpečení je to hlavní, nespoléhejte se jen na to. Zaměřte se na rodinu a komunikujte spolu o nadcházejícím životním období! Se svými blízkými se kromě jiného bavte i o tom, jak si své stáří představujete a jakou roli v něm budou hrát váš partner/partnerka, děti i ostatní blízcí. Starejte se také o vám blízké seniory! Hovořte s nimi a sdílejte  navzájem životní zkušenosti. I dnešní senioři pro vás mohou představovat vzor a inspiraci do života i do samotného stárnutí. Nezapomínejte ani na své fyzické a duševní zdraví!  Zkuste se starat o své tělo jemně a nenásilně: nehuntujte ho ani příliš intenzivním sportem ani intenzivním nicneděláním, sportujte s mírou. Choďte na preventivní prohlídky (i když je tak těžké si je hlídat), a užívejte si zdravý pohyb v přírodě.",
    },
    {
        name: "Odevzdaní trpitelé",
        desc: "Sice vnímáte rizika stáří vcelku intenzivně, nemáte ale dost vlastních schopností a/nebo kapacit, abyste s nimi účinně bojoval/a k zajištění spokojeného stáří. Dnešní náklady na zabezpečování na stáří se vám jeví jako nepřijatelné a rizika stáří jako neodvratná. Zároveň, jste si vědomi svého (trochu) hazardního přístupu ke stáří. Své úsilí musíte věnovat hlavně řešení aktuálních problémů svého života, k čemuž vám často chybí dostatečné finanční zdroje. Na dlouhodobější budoucnost, zdá se v tuto chvíli, nezbývá…. Pasívních trpitelů je spolu s vámi v dané věkové skupině 26 %.",
        recom: "Stáři je životní etapa, ke které máte už docela blízko, je potřeba si to přiznat a být aktivnější! Finance jsou sice důležitá část procesu zabezpečovaní na stáří, ale důstojný důchod, to naštěstí nejsou jen peníze! O stáří můžete přemýšlet i v kontextu jiných součástí života, kterým stoji za to se věnovat. Třeba sociální vztahy: pečujte o rodinné zázemí, jak to jen jde, i o vztahy se seniory, potkávejte se s kamarády! Mezilidské vztahy - to je síla, která vám může v budoucnu pomoci: můžete na nich stavět. Myslete také na své fyzické a duševní zdraví!  A nestyďte se poradit buď s někým blízkým, nebo i odborníkem o svých případných problémech i pocitech spojených se stárnutím a stářím. Nechat nahlédnout do svého světa někoho jiného  - někdy bývá úplně cizí, ale důvěryhodný člověk lepší variantou než někdo, kdo vás zná a koho znáte vy.",
    },
    {
        name: "Bezstarostní jezdci",
        desc: "Rizika stáří si moc nepřipouštíte, ale přestože se vám zdají být příliš vzdálená či mlhavá, není to tak! Máte pocit nedostatečné kontroly nad riziky stáří a asi i kvůli tomu se ani nijak vlastními silami nesnažíte proti nim zajišťovat, nesledujete ani finanční situaci své domácnosti. Ke stáří přistupujete jako k něčemu, co je dané osudem. Odmítáte riskovat a řešit problémy tykající se období, ke kterému pomalu směrujete. Žijete dneškem asi více než je zdrávo a spolu s vámi v tom lítá 26 % vaší věkové skupiny.",
        recom: "Stáří je tak trochu za rohem, a tak je čas si rizika (a příležitosti) spojené s tímto obdobím připouštět. Nemusíte se ale bát. Existuje několik cest, kterými se lze pomalu připravovat na důchod. Především, zaměřte se na rodinu a komunikujte spolu o rodině i nadcházejícím životním období, to v našich rodinách často chybí. Se svými blízkými se kromě jiného bavte i o tom, jak si své stáří představujete a jakou roli v něm budou hrát oni (váš partner/partnerka, děti). Starejte se také o vám blízké seniory. Hovořte a sdílejte  vzájemně zkušenosti se starší generací. Stále platí, že i oni mohou představovat vzor a inspiraci do života i samotného stárnutí, nebo v horším případě i odstrašující příklad. Samozřejmě myslete na finanční zabezpečeni. Existuje několik možnosti, jak se na období stáři finančně zabezpečit – dodatečné spořeni, pojištěni, investovaní… nikdy není příliš pozdě, vždy je však třeba zvážit rizika. Věnujte se svému fyzickému a duševnímu zdraví: jakákoliv aktivita je dobrá. Ale začněte např. sportovat, ovšem s mírou a užívejte si zdravý pohyb v přírodě. Vyskytne-li se nějaký vážnější životní problém, neváhejte oslovit psychologa či terapeuta. Ověřte také, jaké preventivní prohlídky a programy nabízí zdravotní pojišťovny. Prevence je ta nejlepší volba, která se prokazatelně odráží na dlouhodobé kvalitě života.",
    },
    {
        name: "Ostražití hlídači",
        desc: "Je pro vás charakteristická vysoká míra vnímavosti (ostražitosti) vůči předpokládaným rizikům stáří. Máte v zásadě připravenou komplexní strategií zabezpečování na stáří, které se relativně rychle přibližuje. K problému stáři přistupujete jako k životní výzvě. Je pro vás důležitá racionální kalkulace a hlídání možných ztrát a nákladů na jejich eliminaci. Chcete byt manažerem rizik vlastního stárnutí. Podobných ostražitých hlídačů jako jste vy je ve vaší věkové skupině 28 %.",
        recom: "Sice víte, jak na to, ale stále ještě můžeme něco doporučit i vám. Především – stáří, které je už tak trochu za rohem, nemusí znamenat jen problémy. Je to také váš čas, který můžete využít podle svých představ. Máte pocit, že už nic nového nechcete nebo nepotřebujete zkoušet? Zaměřte se na rozšíření svých volnočasových aktivit třeba o nenáročné kurzy vaření, ručních prací, nebo zkuste nějaký sport či venkovní aktivitu, na kterou nikdy nebyl čas a prostor. Můžete se také vzdělávat i zadarmo, online a celoživotně. Vzdělání otevírá nové možnosti i pro starší generace. Myslete také na sebe. Vyskytne-li se nějaký vážnější životní problém, neváhejte oslovit psychologa či terapeuta. Ověřte také, jaké preventivní prohlídky a programy nabízí zdravotní pojišťovny. Prevence je ta nejlepší léčba. A nezapomeňte, že když se cítíte dobře, má to dobrý vliv na vaše blízké!"
    }
  ],
  [
    {
      name: "Spontánní aktivisté (hybatelé)",
      desc: "Vyznačujete se výrazným deficitem vnímání rizik stáří a zároveň vysokou mírou a komplexností preventivních strategických aktivit. Rizika jako by pro vás nebyla, ale váš životní styl proti nim „bojuje“ tak trochu automaticky. Svým spontánním aktivismem intuitivně rizika omezujete. To znamená, že s riziky stáří bojujete jen jaksi mimochodem, protože máte odpor k rizikům jako takovým. Riskování je pro vás obecně nežádoucí chování, a proto ve svém každodenním životě standardně uplatňujete zásadu předběžné opatrnosti. Přístup spontánního aktivisty k přípravě na stáří je typický pro 15% dospělých obyvatel ČR ve vašem věku.",
      recom:
        "Na první pohled se může tento přístup jevit jako ideální – člověk se nezatěžuje stresem ze stáří a zároveň si buduje potenciál čelit rizikům, která stáří přináší.  Vaše tak trochu bezděčná opatrnost ohledně životních rizik ale nemůže skutečné stáří oddalovat do nekonečna. Je velmi pravděpodobné, že povede k prodloužení doby, kdy budete žít s větším či menším zdravotním omezením. Proto bude vhodné připravit se na specifická rizika stáří se zdravotním handicapem a sníženou soběstačností. Je také pravděpodobné, že se nebudete moci spolehnout jen na pomoc rodiny a svých blízkých, ale budete využívat i systém zdravotních a sociálních služeb, což vyžaduje specifické informace a dovednosti, které budete muset získat, abyste se v něm dokázali dobře zorientovat. Jasnou výhodu bude mít ten, kdo bude znát svá práva a možnosti a také kdo naspoří (nebo má naspořeno) dost peněz na zaplacení specializované péče přizpůsobené na míru. A konečně také ti, kteří bydlí v místě, kde je tato péče dostupná.",
    },
    {
        name: "Odevzdaní trpitelé",
        desc: "Rizika stáří vnímáte vcelku intenzivně, ale nemáte dostatek schopností a prostředků a ani motivaci, abyste mohli vyvíjet propracovanější strategie, které by vám mohly zaručit spokojené stárnutí. Rizika stáří podstupujete nedobrovolně, strádáte ekonomicky, zdravotně i sociálně a nezbývá vám nic jiného, než doufat, že stát nebo někdo jiný se o vás postará. Své úsilí musíte věnovat hlavně překonávání překážek aktuálního života. Obrazně řečeno, žijete tak trochu na dluh. Přístup odevzdaného trpitele k přípravě na stáří je typický pro 22% dospělých obyvatel ČR ve vašem věku.",
        recom: "Pokud čtete toto doporučení, není to s vámi až tak zlé, ale na (opravdu) stará kolena vám hrozí nejen nedostatek peněz, ale i sociální izolace. Ale vy nejste bezmocní a můžete svoji prozatímní pasivitu prolomit. Začněte tím, že budete o svém životě ve stáří více mluvit s vaší rodinou a lidmi z vašeho sousedství, protože budete potřebovat jejich neformální péči, když bude vaše soběstačnost stářím omezena. Choďte více do společnosti, pořiďte si třeba domácího mazlíčka, který vás „vytáhne“ mezi lidi. Zapojte se do života sousedské komunity např. prostřednictvím drobné sousedské výpomoci. Prozkoumejte možnosti navštěvovat různé kluby či spolky. Pokud je to to možné, přivydělávejte si. Vzhledem k úrovni vašich příjmů vás v důchodu (pokud v něm ještě nejste) velmi pravděpodobně očekávají problémy se zaplacením nákladů na bydlení. Pokud bydlíte v podnájmu, v jednočlenné domácnosti či ve vlastním, ale velkém bytě, tak je to téměř jisté. Musíte se připravit i na riziko ztráty domácího prostředí, na které jste si zvykli. Nebojte se v rámci rodiny nastolit otázku vícegeneračního bydlení. Když to nepřichází v úvahu, začněte se zajímat o rezidenční zařízení a služby pro seniory nejlépe v místě vašeho bydliště. Tam kde máte svoje kořeny. Ve hře je také možnost stárnutí ve společenství místních seniorů např. formou sdíleného bydlení, které je založeno na vzájemné podpoře a pomoci lidí jako jste vy. Nerezignujte na sledování vašich financí. Rozhodně se vyvarujte zadlužování. I drobné půjčky mohou být začátkem úvěrového kolotoče. Za to žádný dárek, dovolená či zážitek nestojí!!! Když je budoucnost nejistá, není to důvod k utrácení, ale k opatrnosti. Hodně také záleží na vašem životním stylu. Snažte se omezit „neřesti“, jako jsou kouření a alkohol.",
    },
    {
        name: "Bezstarostní jezdci",
        desc: "Je to trochu paradox, ale i ve vašem věku se vám rizika stáří zdají být příliš mlhavá, abyste se jimi zabývali a zajišťovali se proti nim. Nechcete se zatěžovat řešením problémů, které možná ani nepřijdou a ponecháváte věci tak, jak samy běží. Žijete v přesvědčení, že stejně je už vše napsáno v knize osudu, a že na tom svým úsilím už nic nezměníte. Jste to dobrovolní nositelé rizik stáří, kteří se spoléhají, že to s nimi pod ochranným deštníkem systému státní péče stejně nějak dopadne, případně to zvládnete sami. Věříte, že budete mít štěstí a váš život bude alespoň snesitelný. Přístup bezstarostného jezdce k přípravě na stáří je typický pro 31% dospělých obyvatel ČR ve vašem věku, což je možná trochu překvapení, ale možná jde ve vašem případě o projev určitého smíření se životem.",
        recom: "Bezstarostní jezdci ve vašem věku jsou obvykle nazíráni jako ti nejpravděpodobnější kandidáti na pozici tzv. „prekérních seniorů“, kteří jsou už po šedesátce nezaměstnatelní, důchod jim nestačí na pokrytí jejich potřeb, nemají rezervy pro řešení mimořádných událostí a nemohou účinně využít ani rodinné či komunitní zázemí. To všechno ani ne tak kvůli nízkým příjmům, ale kvůli vyšším výdajům, spojených s životním stylem, který se díky svému laxnímu přístupu k rizikům stáří, nesnaží nijak omezovat. I když jen málokdo z bezstarostných jezdců se obává, že ve stáří bude na obtíž svým blízkým, pravdou je, že laxnost k zabezpečování se na stáří přináší zvýšené riziko rychlé ztráty soběstačnosti a schopnosti chovat se autonomně. Ale nemusí to tak nutně být! Na posilování vlastní odolnosti vůči rizikům stáří nemusíte rezignovat. Ano, berete stáří jako danost, ale vaše aktivita ji může přinejmenším ovlivnit. V důsledku životního stylu zaměřeného spíše na vlastní potěšení, můžete být také zaskočeni otázkou naplněnosti svého života, která se naléhavěji vynořuje v období křehkého stáří. Opravdu věříte, že když člověk ve stáří nemá stejně kvalitní život jako předtím, tak už nic nemá cenu? Věřte raději tomu, že posilování schopnosti čelit rizikům stáří alespoň částečnou změnou životního stylu se vyplatí. Zvýšená péče o vlastní zdraví či finanční zabezpečení a orientace na pomoc druhým zahání pocity promarněného času, přináší větší spokojenost a projevy uznání okolí, což k důstojnému prožití stáří jistě patří.",
    },
    {
        name: "Ostražití hlídači",
        desc: "Jste hodně vnímaví vůči rizikům stáří a zároveň se vyznačujete intenzivní a relativně komplexní strategií zabezpečování na stáří. Rizika stáří berete jako životní výzvu. Vidíte v nich reálnou hrozbu, kterou je potřeba ostražitě hlídat a mít ji pod kontrolou. Jste přesvědčení, že aktivní příprava na rizika života ve stáří se vyplatí. Snažíte se tato rizika snižovat, co to jen jde, aby vaše jistota prožití naplněného a dlouhého stáří byla co největší. Přístup ostražitého hlídače k přípravě na stáří je typický pro 32% dospělých obyvatel ČR ve vašem věku.",
        recom: "Z perspektivy prožití plnohodnotného stáří je to přístup velmi prozíravý a pozitivní, a pokud je to možné, měli byste se ho držet i nadále. I tento přístup však má svá úskalí. Především byste se měli vyvarovat stresu ze stáří. Měli byste přijmout to, že s postupujícím stářím bude nutné ve vašich aktivitách zařadit přece jen nižší rychlostní stupeň, jinak vám hrozí pracovní přetížení (v případě, že stále ještě pracujete) ale také předčasná fyzická či psychická vyčerpanost. I aktivní stárnutí má své limity. Prostředky nastřádané na zabezpečení ve stáří byste totiž místo na vychutnávání aktivního odpočinku museli využít spíše na řešení svých zdravotních problémů. Výhodu mají ti, kteří nepracují manuálně, ti mohou v pracovních aktivitách pokračovat déle. Ale i oni by měli upravit svůj životní styl tak, aby byly jejich duševní a fyzické aktivity v rovnováze. A v rovnováze byste měli udržovat i jednotlivé součásti své strategie zabezpečování se na období křehkého stáří tj. finanční, zdravotní i společenské či rodinné. Je zřejmé, že jen peníze samotné k plnohodnotnému stáří nevedou."
    }
  ],
  [
    {
      name: "Spontánní aktivisté (hybatelé)",
      desc: "Patříte k těm lidem, kteří jsou aktivní ve vztahu k rizikům stáří, přestože sami pro sebe tato rizika nevnímáte jako příliš palčivá. Je to strategie, která se opírá pravděpodobně o předběžnou opatrnost a dobrý zvyk jednat aktivně, spíše než o strach. A nemění se to i s věkem. Naštěstí, máte dobrou životní úroveň, což také ovlivňuje vaše vnímání problémů spojených se stárnutím. Do kategorie aktivistů jsme zařadili podle dat našeho výzkumu 19 % respondentů starších 69 let. Jde tedy o relativně nejmenší část populace ve vašem věku.",
      recom:
        "Jen také dále! Jestli budete dělat to, co děláte, prožíváte své stáří dobře a důstojně. Co ještě byste mohla/a dělat právě nyní? Třeba něco, na co jste nikdy nenašli čas a prostor – nový koníček, sport, nezrealizovaný výlet? Vsaďte na mezigenerační solidaritu a komunikaci – mate hodně zkušenosti, předejte je jiným jako inspiraci, jak se dobře a v klidu připravit na stáři, jak žít plnohodnotní život po 70. Pečujte o sebe a svou duševní pohodu. Je to nejlepší pojistka na nečekané životní události. Ale zkuste se nevyhýbat i možná palčivějším otázkám pozdního stáří, pomůže to nejen vám, ale i vašim blízkým. Jde o aktivitu, která není snadná, ale vy sami musíte nejlépe vědět, že v životě není vždy jen to, co je snadné a zábavné…..",
    },
    {
        name: "Odevzdaní trpitelé",
        desc: "Jste to vy, kdo sice rizika (svého) stárnutí vnímáte silně, ale intenzita vašeho jednání, které by mohlo těmto rizikům čelit, tomu ale neodpovídá: stáří se bojíte, ale nic se svými obavami neděláte. Snášení rizik stáří je pro vás alternativou k velmi pravděpodobným ztrátám, ke kterým by jinak došlo, kdybyste všechny zdroje nemohli použít na své dnešní nezbytné životní výdaje. Život pro dnešek je vaší životni strategie, a to přes to že výzvám stárnutí čelíte každý den. Odhadujeme, že mezi lidmi, kterým již bylo 69 let, je takovýchto „trpitelů“ okolo 31 %, což z vás dělá „příslušníka“ největší skupiny v tomto věku.",
        recom: "To že na rizika nereagujete, je dosti pravděpodobně důsledkem nedostatku zdrojů a sil k jednání. Ale fakt, že jste ve svém životě došel/došla až sem, je pozitivní signál. Přestože vy osobně zdroje (finanční, společenské nebo zdravotní) nemáte dostatečné, je možné v tomto případě jednat ve spolupráci s někým jiným: využít třeba pomoc rodiny či širšího sociálního okolí. Péče o Vaše rodinné a společenské vazby je rozhodně prospěšnou investicí do budoucnosti – nejen do budoucnosti Vaší, ale i té jejich. Můžeme Vám také doporučit, abyste zvážili uspořádání Vašich přání týkajících se Vašeho majetku či zdraví. Lidé často tyto věci odkládají, ale jejich promyšlení a sepsání může pomoci Vám i Vašemu okolí. Víme, není to něco, co by člověk chtěl řešit, ale je to něco, co vám pomůže se tak trochu vymanit ze své (mírné?) odevzdanosti.",
    },
    {
        name: "Bezstarostní jezdci",
        desc: "Bezstarostní jezdci je naše pojmenování pro vás, kteří vnímáte rizika stárnutí spíše méně intenzivně a stejně tak málo intenzivní a propracované jsou vaše strategie jednání ve vztahu k těmto možným rizikům. Když rizika nejsou, není s nimi, co dělat. Ale zatímco mezi nejmladšími ročníky jsou „bezstarostní“ spíše ti, pro které je stáří vzdálenou budoucností, ve Vaší věkové skupině už jde dost možná spíše o výraz optimistické a poklidné smířenosti s podzimem života. Mezi bezstarostné jezdce jsme v našem výzkumu zařadili přibližně 29 % lidí, kterým bylo 69 let nebo více.",
        recom: "Z výzkumů je známé, že zapojení do společenského života je výhodné z hlediska psychické pohody i jako forma zabezpečení. Ti kdo mají více kontaktů a přátelských vazeb jsou na tom lépe. Stejně tak je možné využít i dobře známé formy podpory zdraví – myslet na prevenci, informovat se a snažit se vyhýbat tomu, co zejména aktuální zdraví prokazatelně poškozuje. Obecně, je potřeba se zamyslet nad tím, zda nepotřebujete ve svém životě přece jen něco zařídit. Míníme zde například některé z těch záležitostí, na které lidé neradi myslí, protože se týkají těch „posledních věcí v životě“, na které je ale radno myslet, jako je sepsání závěti či vytvoření soupisu přání o léčbě na konci Vašeho života. Věřte, že to pomůže i lidem kolem Vás. Možná si i vy sám/sama potřebujete v tomto smyslu utřídit svoje myšlenky. A nebojte se, řešení těchto věcí neznamená, že vás někdo odepisuje, ale naopak znamená to, že vás bere vážně.",
    },
    {
        name: "Ostražití hlídači",
        desc: "Jste ti, kteří velmi silně vnímají rizika stáří a zároveň se také snaží intenzivně a promyšleně na tato rizika připravovat, aby k jejich realizaci vůbec nedošlo nebo se co nejvíc oddálila a zmírnila. Ve Vaší věkové skupině je přibližně 20 % ostražitých hlídačů, kteří se svým stářím aktivně pracují a nerezignovali na něj.",
        recom: "Jde rozhodně o aktivní přístup zaměřený na budoucnost, o přístup, který vychází z faktu, že i ve vyšším věku můžete aktivně jednat a ovlivňovat podmínky svého života. Důležitý pro vedení vlastního života je pocit, že člověk je tím, kdo má možnost o svém životě rozhodovat. Některé faktory zdravého stárnutí jsou obecně známé, jako například vyvážená strava a přiměřený pohyb – sport, procházky v přírodě, ale jiné tak trochu unikají pozornosti, například to, že důležitým faktorem posilujícím zdraví je přetrvávající pocit smyslu života, s tím spojená životní spokojenost a také fungující sociální kontakty – vsaďte hlavně na mezigenerační vazby: komunikujte s mladšími generacemi, a i když to možná není na první pohled patrné, vyplatí se tato komunikace nejen vám. Možná vás jejich osvěžující přístup k životu ulehčí nést břímě životní ostražitosti."
    }
  ],
];

export default hodnoceni;