const hodnoceni = [
  [
    {
      name: "Spontánní aktivisté",
      share:
        "Podobný přístup jako vy má k přípravě na stáří 27 % dospělých obyvatel ČR ve vašem věku.",
      desc:
        "<p>Rizik stáří se neobáváte, ale zároveň se na ně spontánně připravujete. Váš přístup k životu funguje sám o sobě jako prevence.</p><p>S riziky se vyrovnáváte jaksi mimochodem. Riskování je pro vás obecně nežádoucí, a proto ve svém každodenním životě standardně uplatňujete zásadu předběžné opatrnosti.</p>",
      recom:
        "<p>Během „čekání“ na stáří se může leccos stát, a to jak v pozitivním, tak v negativním smyslu. Nicméně pokud budete dělat to, co děláte doposud a v dalších letech přidáte cílenější aktivitu či aktivity, velmi zvyšujete své šance na dobře prožívané a důstojné stáří.</p><p>Aktuálně se můžete soustředit třeba na mezigenerační solidaritu a komunikaci.  Podpora starším členům vaší rodiny (babičky, dědečkové, tety i strýcové….) případně i neznámým lidem formou dobrovolnické činnosti může vést k získání  podstatných životních zkušeností. I tímto způsobem můžete zvýšit svou připravenost na život ve stáří.</p>",
    },
    {
      name: "Odevzdaní trpitelé",
      share:
        "Přístup odevzdaného trpitele k přípravě na stáří je typický pro 15 % obyvatel ČR ve vašem věku. Ve své věkové skupině patříte k typu, který je nejméně častý.",
      desc:
        "<p>Navzdory svému mládí vnímáte rizika stáří intenzivně. Nejspíš nemáte ve svém okolí nikoho, u koho se už tato rizika změnila v reálný stav, a i proto vás myšlenky na stárnutí trochu děsí.</p><p>Přestože se stáří obáváte, aktivně žijete hlavně pro dnešek. Aktuálně nemáte dost schopností ani prostředků a možná ani motivaci, abyste mohli rozvíjet nějaké strategie nebo alespoň jednotlivé činnosti, které by vám (po)mohly zvýšit šanci na spokojené stáří. Zatím se zdá, že vám nezbývá nic jiného než doufat, že se o vás postará stát.</p>",
      recom:
        "<p>Zkuste se obrátit na někoho, komu věříte, a pobavit se s ním o vašich vyhlídkách na stáří. Můžete vyhledat i profesionála – mentora, poradce online i offline. Hlavní je se nebát. A samozřejmě pokud žijete v dobrém rodinném zázemí, mluvte o tom se svými blízkými. Jaké obavy mají vaši rodiče a prarodiče a co s nimi dělají?</p><p>O obavách ze stáří nestačí jen mluvit, zkuste i něco málo udělat: Třeba si odkládat část peněz stranou, začít cvičit nebo se častěji scházet s přáteli a budovat si vlastní okruh blízkých lidí, protože ve stáří se jejich důležitost zvyšuje.</p>",
    },
    {
      name: "Bezstarostní jezdci",
      share:
        "Přístup bezstarostného jezdce k přípravě na stáří je typický pro 34&nbsp;% dospělých obyvatel ČR ve vašem věku. Patříte do skupiny, která je z hlediska přípravy na stáří největší.",
      desc:
        "<p>Rizika stáří se vám zdají příliš mlhavá a asi vzdálená na to, abyste se jimi zabývali. Nechcete se zatěžovat řešením problémů, které jsou příliš daleko, a ponecháváte věci tak, jak samy běží.</p><p>Jste nejspíš fatalisti: vše už je napsáno v knize osudu a vlastním úsilím na tom už nic moc nejde změnit. Jste dobrovolnými nositeli rizik stáří, a&nbsp;možná nejen jeho. Spoléháte, že to s vámi pod ochranným deštníkem systému státní péče nějak dopadne. Věříte, že budete mít třeba štěstí a&nbsp;váš život ve stáří nepřekročí hranice katastrofy.</p>",
      recom:
        "<p>Užívat si života naplno právě teď je hodnota důležitá pro lidi napříč věkovými skupinami. Jste si ale vědomi toho, že tímto způsobem se poštěstí zestárnout ve zdraví jen málokomu?</p><p>Asi o následcích svého hédonistického přístupu k životu moc nepřemýšlíte. Ty sice nemusí být vidět hned, ale zároveň se s nimi můžete setkat i mnohem dříve než ve stáří. Nechcete s tím něco udělat? Pokud nežijete jako vzor zdravého životního stylu, nešlo by vaše neřesti alespoň částečně eliminovat? Ne všechno najednou, ale třeba jen jednu.</p><p>Pokud utrácíte bez rezerv, zkuste to jinak. Jak dlouho vám přináší potěšení nová věc nebo zážitek? Zkuste si něco málo odepřít, třeba jen na omezenou dobu a uvidíte, co to s vámi udělá. Ano, času máte dost, ale co zkusit udělat něco hned a být za sebe alespoň částečně zodpovědný?</p>",
    },
    {
      name: "Ostražití hlídači",
      share:
        "Přístup ostražitého hlídače k přípravě na stáří je typický pro 24 % dospělých obyvatel ČR ve vašem věku, což je docela velký podíl, uvážíme-li, jak vzdálené stáří pro vás je.",
      desc:
        "<p>Je pro vás charakteristická vysoká míra vnímavosti vůči rizikům stáří: nejen, že je vidíte, ale také jsou pro vás zdrojem obav. A proto se s tím snažíte něco dělat. Máte vlastní, celkem bohatě rozvinutou strategií zabezpečování na stáří.</p><p>Rizika stáří berete jako životní výzvu. Vidíte v nich reálnou hrozbu, kterou je potřeba ostražitě hlídat a mít ji pod kontrolou. Jste přesvědčeni, že aktivní příprava na rizika života ve stáří již teď se vyplatí a ve vašem případě se může s přibývajícím věkem příprava ještě zintenzivnit. Snažíte se tato rizika snižovat, co to jen jde, abyste měli jistotu prožití naplněného stáří.</p>",
      recom:
        "<p>Je moc dobře, že přemýšlíte o svém životě v dlouhodobém výhledu. A je dobře, že si uvědomujete rizika spojená se stárnutím. A úplně nejlepší je, že s tím něco vědomě děláte. Obojí je pro vaši generaci ne úplně typické a určitě sám/sama víte, že stereotypy o mladých s takovou eventualitou ani nepočítají a přičítají vám hlavně mladickou lehkovážnost…</p><p>Možná jste takoví, protože máte dobrý příklad ze svého okolí.  Možná máte rodiče, kteří vám už od dětství platili důchodové připojištění, nebo berete rady svých starších členů rodiny vážně a nepouštíte je jedním uchem dovnitř a druhým ven. Nebo jste prostě „přirozeně“ zodpovědní.</p><p>Těžko vám můžeme radit, abyste dělali něco víc. Máme ale jednu otázku k zamyšlení: Berete život spíše jako dar, se vším všudy i se stářím? Pokud ano, doufáme, že ho prožíváte bez přílišného stresu, a to nejen ze stárnutí.</p>",
    },
  ],
  [
    {
      name: "Spontánní aktivisté",
      share:
        "Přístup spontánního aktivisty k přípravě na stáří je typický pro 24 % dospělých obyvatel ČR ve vašem věku.",
      desc:
        "<p>Gratulujeme! Váš finanční i sociální kapitál, spektrum vašich aktivit a vaše životní úspěchy vás zatím chrání proti rizikům stáří. Patříte k lidem, kteří se sice stáří příliš neobávají, ale zároveň vaše spontánní životní aktivity celkem spolehlivě fungují jako prevence vůči s ním spojeným rizikům.</p><p>S riziky stáří bojujete jen jaksi mimochodem – vaše strategie je obecná, nikoli konkrétně zacílená. Ve svém každodenním životě standardně uplatňujete zásadu předběžné opatrnosti, takže kdykoli riskujete, třeba při investování, můžete se spolehnout na solidní zajištění v jiných oblastech.</p>",
      recom:
        "<p>Třebaže máte rizika více méně dobře rozložená a pod kontrolou, je dobré počítat s tím, že rizika stáří mají svá specifika. Komunikujte se staršími generacemi o jejich očekáváních a potřebách, abyste si sami utříbili svou vlastní představu o stárnutí.</p><p>Je možné, že existují opatření, která jste dosud nevnímali jako důležitá, ale v delší perspektivě se mohou projevit jako klíčová. Začněte uvažovat o přeskupení vašich rodinných aktiv a statků s výhledem na několik desetiletí dopředu. Uspořádání, které se vám zdá v současnosti jako optimální, nemusí být optimální v horizontu deseti patnácti let.</p><p>Pokuste se vytyčit si cíle, kterých chcete do svého stáří a během něj dosáhnout. Naplánujte si alespoň v hrubých obrysech, co všechno budete potřebovat. Začněte se zajímat o to, jak fungují různé zdravotnické a sociální služby pro seniory. Nejen vzhledem k vaší budoucí situaci, ale především v mnohem aktuálnější souvislosti s vašimi blízkými, kteří se dostávají do životní etapy křehkého stáří nebo už v ní jsou.</p>",
    },
    {
      name: "Odevzdaní trpitelé",
      share: "Ve vaší věkové skupině je odevzdaných trpitelů 18 %.",
      desc:
        "<p>Patříte mezi ty, kteří sice vnímají rizika stáří vcelku intenzivně, ale nemají dost schopností a prostředků, případně motivace, aby mohli vyvíjet komplexnější strategie, které by jim mohly zaručit spokojené stáří.</p><p>Strádáte ekonomicky, zdravotně nebo sociálně a zdá se, že vám nezbývá nic jiného než doufat, že se o vás na stará kolena postará stát. Snášení rizik stáří je pro vás přijatelnější alternativou k aktuálně vynaložené snaze, kterou si z různých důvodů nemůžete nebo nechcete dovolit. Žijete tedy hlavně dneškem, protože dělat něco pro budoucnost je pro vás nyní příliš složité.</p>",
      recom:
        "<p>Život se s vámi nemazlí a ani vyhlídky na stáří zatím nejsou nejrůžovější. Není však všem dnům konec. Nepropadejte zádumčivosti – jste dosud ve věku, kdy se dá leccos změnit a obrátit k lepšímu. Klíčové je, že si rizika stáří uvědomujete a chcete s nimi něco dělat.</p><p>Uvažujte, na jakých pilířích, třebaže se zatím zdají vratké, můžete do budoucna stavět. Vezměte do úvahy svou finanční situaci, zdravotní stav a síť vašich známých či přátel.</p><p>Pokud se nacházíte v tíživé ekonomické situaci, zkuste provést revizi svých přijmů a výdajů. Existuje možnost získat lépe placenou práci nebo výhodnější bydlení ve vašem okolí, nebo třeba v jiném regionu? Nejsou ve vašich výdajích položky, které by se daly vypustit nebo odložit na později? Máte možnost část svého volného času věnovat péči o své zdraví nebo třeba sportu? Je ve vašem okolí někdo, na koho se můžete spolehnout a kdo to s vámi myslí dobře? Pokud ne, měli byste se snažit část volného času trávit ve společnosti a vybudovat si síť přátel, se kterými budete sdílet své starosti. Nemusí  to být drahé ani vyčerpávající – a přátele z mládí ve stáří jako když najdeš. </p><p>Nejlepší a nejvěrnější oporu ovšem obvykle naleznete ve své rodině. Proto byste měli věnovat zvýšenou pozornost rodinným vztahům a vazbám, které vás v nejtěžších momentech podrží. V případě, že rodinu nemáte, nebo se s rodinou z nějakého důvodu nestýkáte, stále máte příležitost založit si rodinu vlastní. Děti vždy přináší naději. Nejen z našeho výzkumu vyplývá, že právě děti budou hrát ve vašem stáří jen těžko nahraditelnou úlohu. Pokud cítíte, že svou situaci nezvládáte, existuje řada organizací – státních i neziskových, na které se můžete obrátit o pomoc. Nejsou to sexy rady, ale mohou fungovat.</p>",
    },
    {
      name: "Bezstarostní jezdci",
      share: "Přístup bezstarostného jezdce k přípravě na stáří je typický pro 30 % dospělých obyvatel ČR ve vašem věku. Patříte do skupiny, která je z hlediska přípravy na stáří největší.",
      desc:
        "<p>Rizika stáří se vám zdají příliš mlhavá a vzdálená na to, abyste se jimi zabývali. Nesnažíte se proti nim tudíž zajišťovat. Nechcete se zatěžovat řešením problémů, které jsou daleko a ponecháváte věci tak, jak samy běží. Jste nejspíš fatalisti: vše už je napsáno v knize osudu a vlastním úsilím už na tom nelze nic moc změnit.</p><p>Jste dobrovolnými nositeli rizik stáří, a spoléháte, že to s vámi pod ochranným deštníkem státní péče nějak dopadne. Věříte, že budete mít třeba štěstí a váš život ve stáří nepřekročí hranice katastrofy. Je samozřejmě otázka, zda svůj přístup ke stáří ještě radikálně nezměníte. Je nejvyšší čas.</p>",
      recom:
        "<p>S trochou nadsázky lze vaši současnou strategii přirovnat ke skoku z letadla bez padáku. Zažijete možná neskutečný pocit volnosti a maximální vzrušení a není vyloučeno, že vás na poslední chvíli někdo zachytí a vy dopadnete do měkkého. Na druhou stranu se nesmíte divit, pokud dopadnete velmi tvrdě. S přibývajícím věkem totiž počet možností na záchranu klesá. Ač o tom možná nevíte, vystavujete se riziku neuspokojivého stáří a dost možná i zbytečné předčasné smrti.</p><p>Dobrá zpráva je, že stále máte čas věci změnit. Začněte tím, že si promluvíte s lidmi ze svého nejbližšího okolí. Zeptejte se rodičů nebo prarodičů, jak se jim žije, a zda by si bývali nechtěli některé věci zařídit jinak. Přemýšlejte o tom, zda byste chtěli prožít stáří podobně jako oni: jak vypadá váš „ideál“? A co pro něj můžete udělat.</p><p>Své stávající vztahy s přáteli a se členy rodiny se pokuste maximálně upevnit. Pokud ještě nemáte děti, zamyslete se, zda je skutečně ve stáří nebudete „potřebovat“. Z našeho i dalších průzkumů vyplývá, že role dětí bývá při zajišťování uspokojivého stáří rodičů jen těžko zastupitelná. Pokud děti nemůžete nebo nechcete mít, zaměřte se na budování jiných silných sociálních vztahů.</p><p>V případě, že vám tyto v budoucnu budou chybět, bude pro Vás zajištění slušného standardu stáří drahé. Musíte tedy své úsilí napřít do vydělávání většího objemu peněz. Cílem je ušetřit pokud možno čtvrtinu příjmů na investice. Samotný vyšší příjem v současnosti vám totiž nemusí zaručovat i dostatečný příjem ve stáří ve formě státní penze. Můžete začít konzervativně: např. státem podporovaným důchodových připojištěním. Odvážnější investicí může být nákup nemovitostí nebo dluhopisy, kde lze předpokládat slušné zhodnocení. Můžete investovat po menších částkách a nezapomenout ověřit si důvěryhodnost subjektu, jenž daný produkt nabízí. Ve vašem věku si ještě můžete dovolit investovat i do krátkodobě rizikovějších instrumentů, které ovšem mohou mít v delším výhledu vyšší výnos.</p><p>V neposlední řadě nepřeceňujte možnosti vašeho těla odolávat různým zátěžím. Vyvarujte se především závislostem na alkoholu a kouření. Investicí, kterou vám nikdo nevezme, jsou peníze vložené do kvalitního jídla s vyváženým obsahem živin a vitamínů a zdravého pohybu. Proč neinvestovat pár stokorun třeba do permanentky do bazénu?</p>",
    },
    {
      name: "Ostražití hlídači",
      share: "Přístup ostražitého hlídače k přípravě na stáří je typický pro 27 % dospělých obyvatel ČR ve vašem věku.",
      desc:
        "<p>Patříte mezi lidi, pro které je charakteristická vysoká míra vnímavosti vůči rizikům stáří a zároveň se vyznačujete intenzivní a relativně komplexní strategií zabezpečování na stáří. Rizika stáří berete jako životní výzvu. Vidíte v nich reálnou hrozbu, kterou je potřeba ostražitě hlídat a mít ji pod kontrolou. Jste přesvědčení, že aktivní příprava na rizika života ve stáří již teď se vyplatí a ve vašem případě se může s přibývajícím věkem příprava ještě zintenzivnit. Snažíte se tato rizika snižovat, co to jen jde, abyste měli větší jistotu naplněného stáří.</p>",
      recom:
        "<p>Jen tak dál! Dobře víte, že rizika stárnutí se nesmí podceňovat. Na druhou stranu strach ze stáří by vás neměl svazovat a být zdrojem přehnaného stresu. Rozhodně by vám neměl zabránit v tom, abyste si užili výhod, které přináší váš stávající věk, případně abyste dokázali čelit jiným akutnějším druhům rizik. Neměli byste především přehlížet aktuální a střednědobé potřeby vaší rodiny, zejména dětí.</p><p>Poměrně brzy budete nejspíš čelit problémům spojeným se stárnutím generace vašich rodičů a prarodičů, kteří se budou posouvat do zranitelnějších věkových kategorií. Je velmi důležité, abyste s nimi navázali otevřenou komunikaci o jejich představách a ideálech spojených se stářím. Jistě je moudré v dostatečném předstihu koordinovat rozhodnutí týkající se rodinného majetku a hodnot. Neměli byste se vyhýbat ani jinak citlivým otázkám spojených se smrtí svých blízkých a vypořádáním všech souvisejících záležitostí. Péče o starší generace a další úkony mohou časem přecházet na vás, a to je vynikající příležitost dát příklad generaci vašich dětí, jak mají postupovat, až se do etapy křehkého stáří dostanete vy, jejich rodiče.</p>",
    },
  ],
  [
    {
      name: "Spontánní aktivisté",
      share: "Podobný přístup k přípravě na stáří vy má 20 % lidí ve vašem věku.",
      desc:
        "<p>Patříte k těm, kteří se sice příliš neobávají rizik stáří, ale zároveň vaše spontánní životní aktivita celkem spolehlivě funguje jako prevence vůči rizikům stáří. To znamená, že s riziky stáří bojujete jaksi mimochodem. Vaše strategie je spíše obecná, nikoli konkrétně zacílená na stáří.</p><p>Rizika stáří se vám jeví jako nepříliš velká, protože máte pocit, že jsou pod vaší kontrolou a že svůj život držíte pevně v rukou. Jste nejspíš dobře materiálně zabezpečení a důvěřujete nejen sobě, ale také statním institucím.</p>",
      recom:
        "<p>Ve svém životě jste aktivní, jen tak dál! Přechod do důchodu, který vás za čas čeká, by neměl znamenat, že nebudete stejně aktivní, jako jste teď.</p><p>Pokud máte pocit, že finanční zabezpečení je to hlavní, nespoléhejte se jen na něj. Zaměřte se na svou rodinu a komunikujte spolu o nadcházejícím životním období! Se svými blízkými se kromě jiného bavte i o tom, jak si své stáří představujete a jakou roli v něm budou hrát váš partner/partnerka, děti i ostatní blízcí.</p><p>Starejte se také o vám blízké seniory. Mluvte s nimi a sdílejte navzájem své životní zkušenosti. </p><p>Nezapomínejte ani na své fyzické a duševní zdraví. Zkuste se starat o své tělo jemně a nenásilně: nehuntujte ho ani příliš intenzivním sportem ani intenzivním nicneděláním, sportujte s mírou. Choďte na preventivní prohlídky (i když je tak těžké si je hlídat), a užívejte si co nejvíc zdravý pohyb v přírodě.</p>",
    },
    {
      name: "Odevzdaní trpitelé",
      share: "Podobný přístup jako vy má k rizikům stáří 26 % lidí ve vaší věkové kategorii.",
      desc:
        "<p>Sice vnímáte rizika stáří vcelku intenzivně, nemáte ale dost vlastních schopností a/nebo kapacit, abyste s nimi účinně bojoval(a).</p><p>Dnešní náklady na zabezpečování na stáří se vám jeví jako nepřijatelné a rizika stáří jako neodvratná. Zároveň jste si vědomi svého poněkud hazardního přístupu ke stáří. Své úsilí ale musíte věnovat hlavně řešení aktuálních problémů, k tomu vám často chybí dostatečné finanční zdroje. Na plánování vzdálenější budoucnosti, vám v tuto chvíli zřejmě nezbývají síly, finanční zdroje ani čas.</p>",
      recom:
        "<p>Stáři je životní etapa, ke které máte už docela blízko. Je potřeba si to přiznat a být aktivnější! Finance jsou sice důležitou částí procesu zabezpečovaní na stáří, ale důstojný důchod naštěstí nejsou jen peníze!</p><p>O stáří můžete přemýšlet i v kontextu jiných součástí života, kterým stoji za to se věnovat. Třeba sociální vztahy: pečujte o rodinné zázemí, jak to jen jde, i o vztahy se seniory, které znáte.</p><p>Potkávejte se co nejčastěji se svým kamarády. Mezilidské vztahy - to je síla, která vám může v budoucnu pomoci: můžete na nich stavět.</p><p>Myslete také na své fyzické a duševní zdraví.  A nestyďte se poradit buď s někým blízkým, nebo i odborníkem o svých případných problémech a pocitech spojených se stárnutím a stářím. Nechat nahlédnout do svého světa někoho jiného může být přínosem - někdy bývá úplně cizí, ale důvěryhodný člověk lepší variantou než někdo, kdo vás zná a koho znáte vy.</p>",
    },
    {
      name: "Bezstarostní jezdci",
      share: "Žijete dneškem asi více než je zdrávo a spolu s vámi je v obdobné situaci 26 % občanů vaší věkové skupiny.",
      desc:
        "<p>Rizika stáří si zatím moc nepřipouštíte, ale přestože se vám zdají být příliš vzdálená či mlhavá, není to tak!</p><p>Pravděpodobně máte pocit nedostatečné kontroly nad riziky stáří a asi i kvůli tomu se ani nijak nesnažíte proti nim zajišťovat, nesledujete ani finanční situaci své domácnosti. Ke stáří přistupujete jako k něčemu, co je dané osudem. Odmítáte riskovat a řešit problémy týkající se období, ke kterému pomalu směrujete.</p>",
      recom:
        "<p>Vaše stáří je už za rohem, a tak je nejvyšší čas si rizika a příležitosti s ním spojené začít připouštět. Nemusíte se ale bát. Existuje několik cest, kterými se lze pomalu připravovat na důchod.</p><p>Především se zaměřte na svou rodinu, pokud ji máte, a komunikujte spolu o nadcházejícím životním období. Se svými blízkými se o tom, jak si své stáří představujete a jakou roli v něm budou hrát oni, váš partner či partnerka a vaše děti.</p><p>Starejte se také co nejvíc o vám blízké seniory. Mluvte s nimi a sdílejte vzájemně zkušenosti se starší generací. Stále platí, že i oni mohou představovat vzor a inspiraci nebo v horším případě i odstrašující příklad.</p><p>Samozřejmě myslete na finanční zabezpečeni. Existuje několik možnosti, jak se na období stáři finančně zabezpečit: dodatečné spořeni, pojištěni, investovaní… Nikdy není příliš pozdě, vždy je však třeba zvážit rizika.</p><p>Věnujte se svému fyzickému a duševnímu zdraví: jakákoliv aktivita je dobrá. Pokud to ještě něeděláte, začněte sportovat, ovšem s mírou a užívejte si zdravý pohyb v přírodě.</p><p>Vyskytne-li se nějaký vážnější životní problém, neváhejte oslovit psychologa či terapeuta. Ověřte také, jaké preventivní prohlídky a programy nabízí zdravotní pojišťovny. Prevence je ta nejlepší volba, která se prokazatelně odráží na dlouhodobé kvalitě života.</p>",
    },
    {
      name: "Ostražití hlídači",
      share: "Lidí s podobným přístupem ke stáří je ve vaší věkové skupině 28 %.",
      desc:
        "<p>Je pro vás charakteristická vysoká míra vnímavosti  a ostražitosti vůči předpokládaným rizikům stáří. Máte připravenou komplexní strategií zabezpečování na stáří, které se rychle přibližuje. K problému stáří přistupujete jako k životní výzvě. Je pro vás důležitá racionální kalkulace a hlídání možných ztrát a nákladů na jejich eliminaci. Chcete být manažerem rizik vlastního stárnutí.</p>",
      recom:
        "<p>Sice víte, jak na to, ale stále ještě můžeme něco doporučit i vám. Především: stáří, které je už tak trochu za rohem, nemusí znamenat jen problémy. Je to také váš čas, který můžete využít podle svých představ.</p><p>Máte pocit, že už nic nového nechcete nebo nepotřebujete zkoušet? Zaměřte se na rozšíření svých volnočasových aktivit třeba o nenáročné kurzy vaření, ručních prací nebo zkuste nějaký sport či venkovní aktivitu, na kterou dřív nebyl čas a prostor.</p><p>Můžete se také vzdělávat i zadarmo, online a celoživotně. Vzdělání otevírá nové možnosti i pro starší generace.</p><p>Myslete také na sebe. Vyskytne-li se nějaký vážnější životní problém, neváhejte oslovit psychologa či terapeuta. Ověřte také, jaké preventivní prohlídky a programy nabízejí zdravotní pojišťovny. Prevence je ta nejlepší léčba. A nezapomeňte, že když se cítíte dobře, má to dobrý vliv na vaše blízké!</p>",
    },
  ],
  [
    {
      name: "Spontánní aktivisté",
      share: "Přístup spontánního aktivisty k přípravě na stáří je typický pro 15% dospělých obyvatel ČR ve vašem věku.",
      desc:
        "<p>Vyznačujete se výrazným deficitem vnímání rizik stáří a zároveň vysokou mírou a komplexností preventivních strategických aktivit. Rizika jako by pro vás nebyla, ale váš životní styl proti nim „bojuje“ tak trochu automaticky. Svou spontánní aktivitou intuitivně rizika omezujete. To znamená, že s riziky stáří bojujete jen jaksi mimochodem, protože máte odpor k rizikům jako takovým. Riskování je pro vás obecně nežádoucí chování, a proto ve svém každodenním životě standardně uplatňujete zásadu předběžné opatrnosti.</p>",
      recom:
        "<p>Vaše tak trochu bezděčná opatrnost ohledně životních rizik  nemůže stáří oddalovat do nekonečna. Je ovšem velmi pravděpodobné, že povede k prodloužení doby, kdy budete žít s větším či menším zdravotním omezením. Proto bude vhodné připravit se na specifická rizika stáří se zdravotním handicapem a sníženou soběstačností.</p><p>Je také pravděpodobné, že se nebudete moci spolehnout jen na pomoc rodiny a svých blízkých, ale budete využívat i systém zdravotních a sociálních služeb, což vyžaduje specifické informace a dovednosti, které budete muset získat, abyste se v něm dokázali dobře zorientovat.</p><p>Jasnou výhodu bude mít ten, kdo bude znát svá práva a možnosti a také kdo naspoří  dost peněz na zaplacení specializované péče přizpůsobené na míru. A konečně také ti, kteří bydlí v místě, kde je tato péče dostupná.</p>",
    },
    {
      name: "Odevzdaní trpitelé",
      share: "Přístup odevzdaného trpitele k přípravě na stáří je typický pro 22% dospělých obyvatel ČR ve vašem věku.",
      desc:
        "<p>Rizika stáří vnímáte vcelku intenzivně, ale nemáte dostatek schopností a prostředků a ani motivaci, abyste mohli vyvíjet propracovanější strategie, které by vám mohly zaručit spokojené stárnutí.</p><p>Rizika stáří podstupujete nedobrovolně – pravděpodobně strádáte ekonomicky, zdravotně či sociálně a nezbývá vám nic jiného, než doufat, že stát nebo někdo jiný se o vás postará. Své úsilí musíte věnovat hlavně překonávání překážek aktuálního života. Obrazně řečeno, žijete tak trochu na dluh.</p>",
      recom:
        "<p>Pokud čtete toto doporučení, je to dobrý signál, ale na (opravdu) stará kolena vám může hrozit nedostatek peněz i sociální izolace. Co s tím můžete dělat? Začněte třeba s tím, že budete o svém životě ve stáří více mluvit s vaší rodinou a lidmi z vašeho sousedství, protože budete potřebovat jejich neformální pomoc, až bude vaše soběstačnost stářím omezena.</p><p>Choďte více do společnosti, pořiďte si třeba domácího mazlíčka, který vás „vytáhne“ mezi lidi. Zapojte se do života sousedské komunity např. prostřednictvím drobné sousedské výpomoci. Prozkoumejte možnosti navštěvovat různé kluby či spolky.</p><p>Pokud je to možné, přivydělávejte si. Vzhledem k úrovni vašich příjmů vás v důchodu, pokud v něm ještě nejste, dost pravděpodobně očekávají problémy se zaplacením nákladů na bydlení.</p><p>Nebojte se v  rodině nastolit otázku vícegeneračního bydlení. Pokud to nepřichází v úvahu, začněte se zajímat o rezidenční zařízení a služby pro seniory v místě vašeho bydliště. Tam, kde máte svoje kořeny. Ve hře je také možnost stárnutí ve společenství místních seniorů např. formou sdíleného bydlení.</p><p>Nerezignujte na sledování svých financí. Rozhodně se vyvarujte zadlužování. I drobné půjčky mohou být začátkem úvěrového kolotoče. Když je budoucnost nejistá, není to důvod k utrácení, ale k opatrnosti.</p><p>Hodně také záleží na vašem životním stylu. Snažte se omezit „neřesti“ jakými jsou kouření a alkohol.</p>",
    },
    {
      name: "Bezstarostní jezdci",
      share: "Přístup bezstarostného jezdce k přípravě na stáří je typický pro 31% dospělých obyvatel ČR ve vašem věku, což je možná trochu překvapení, ale možná jde ve vašem případě o projev určitého smíření se životem.",
      desc:
        "<p> Je to trochu paradox, ale i ve vašem věku se vám rizika stáří zdají být příliš mlhavá, abyste se jimi zabývali a zajišťovali se proti nim. Nechcete se zatěžovat řešením problémů, které možná ani nepřijdou a ponecháváte věci tak, jak samy běží.</p><p>Žijete v přesvědčení, že stejně je už vše napsáno v knize osudu, a že na tom svým úsilím už nic nezměníte. Jste dobrovolní nositelé rizik stáří, kteří se spoléhají, že to s nimi pod ochranným deštníkem systému státní péče stejně nějak dopadne, případně to zvládnou sami. Věříte, že budete mít štěstí a váš život bude alespoň snesitelný. </p>",
      recom:
        "<p>Bezstarostní jezdci ve vašem věku jsou obvykle nazíráni jako ti nejpravděpodobnější kandidáti na pozici tzv. „prekérních seniorů“, kteří jsou už po šedesátce nezaměstnatelní, důchod jim nestačí na pokrytí jejich potřeb, nemají rezervy pro řešení mimořádných událostí a nemohou účinně využít ani rodinné či komunitní zázemí. To všechno ani ne tak kvůli nízkým příjmům, ale kvůli vyšším výdajům spojených s laxním životním stylem.</p><p>I když jen málokdo z bezstarostných jezdců se obává, že ve stáří bude na obtíž svým blízkým, pravdou je, že laxnost v zabezpečování se na stáří přináší zvýšené riziko rychlé ztráty soběstačnosti. Ale nemusí to tak nutně být! Na posilování vlastní odolnosti vůči rizikům stáří nemusíte rezignovat. Ano, berete stáří jako danost, ale vaše aktivita ji může přinejmenším ovlivnit.</p><p>V důsledku životního stylu zaměřeného spíše na vlastní potěšení, můžete být také zaskočeni otázkou naplněnosti svého života, která se naléhavěji vynořuje v období křehkého stáří. Opravdu věříte, že když člověk ve stáří nemá stejně kvalitní život jako předtím, tak už nic nemá cenu? Věřte raději tomu, že posilování schopnosti čelit rizikům stáří alespoň částečnou změnou životního stylu se vyplatí. Zvýšená péče o vlastní zdraví či finanční zabezpečení a orientace na pomoc druhým zahání pocity promarněného času, přináší větší spokojenost a projevy uznání okolí.</p>",
    },
    {
      name: "Ostražití hlídači",
      share: "Přístup ostražitého hlídače k přípravě na stáří je typický pro 32 % dospělých obyvatel ČR ve vašem věku.",
      desc:
        "<p>Jste hodně vnímaví vůči rizikům stáří a zároveň se vyznačujete intenzivní a relativně komplexní strategií zabezpečování na stáří. Rizika stáří berete jako životní výzvu. Vidíte v nich reálnou hrozbu, kterou je potřeba ostražitě hlídat a mít ji pod kontrolou.</p><p>Jste přesvědčení, že aktivní příprava na rizika života ve stáří se vyplatí. Snažíte se tato rizika snižovat, co to jen jde, aby vaše jistota prožití naplněného a dlouhého stáří byla co největší.</p>",
      recom:
        "<p>Z perspektivy prožití plnohodnotného stáří je to přístup velmi prozíravý a pozitivní. Pokud je to možné, měli byste se ho držet i nadále. I tento přístup však má svá úskalí. Především byste se měli vyvarovat stresu ze stáří. Měli byste přijmout to, že s postupujícím stářím bude nutné ve vašich aktivitách zařadit přece jen nižší rychlost. Jinak vám hrozí pracovní a předčasná fyzická či psychická vyčerpanost.</p><p>I aktivní stárnutí má své limity. Prostředky nastřádané na zabezpečení ve stáří byste totiž místo na vychutnávání aktivního odpočinku museli využít spíše na řešení svých zdravotních problémů.</p><p>Výhodu mají ti, kteří nepracují manuálně, ti mohou v pracovních aktivitách pokračovat déle. Ale i oni by měli upravit svůj životní styl tak, aby byly jejich duševní a fyzické aktivity v rovnováze. A v rovnováze byste měli udržovat i jednotlivé součásti své strategie zabezpečování se na období křehkého stáří, tj. finanční, zdravotní i společenské či rodinné. Je zřejmé, že jen peníze samotné k plnohodnotnému stáří nevedou.</p>",
    },
  ],
  [
    {
      name: "Spontánní aktivisté",
      share: "Do kategorie aktivistů jsme zařadili podle dat našeho výzkumu 19 % respondentů starších 69 let. Jde tedy o relativně nejmenší část populace ve vašem věku.",
      desc:
        "<p>Patříte k lidem, kteří jsou aktivní ve vztahu k rizikům stáří, přestože sami pro sebe tato rizika nevnímáte jako příliš palčivá. Je to strategie, která se opírá pravděpodobně o předběžnou opatrnost a dobrý zvyk jednat aktivně, spíše než o strach. A nemění se to ani s věkem. Naštěstí, máte pravděpodobně dobrou životní úroveň, což také ovlivňuje vaše vnímání problémů spojených se stárnutím.</p>",
      recom:
        "<p>Prožíváte své stáří dobře a důstojně. Jen tak dál!</p><p>Co ještě byste mohla(a) dělat? Třeba něco, na co jste nikdy nenašli čas a prostor – nový koníček, sport, nezrealizovaný výlet?</p><p>Vsaďte na mezigenerační solidaritu a komunikaci. Máte hodně zkušeností - předejte je jiným jako inspiraci, jak se dobře a v klidu připravit na stáři, jak žít plnohodnotný život po sedmdesátce.</p><p>Pečujte o sebe a svou duševní pohodu. Je to nejlepší pojistka pro nečekané životní události.</p><p>Ale zkuste se nevyhýbat ani palčivějším otázkám pozdního stáří, pomůže to nejen vám, ale i vašim blízkým. Jde o aktivitu, která není snadná, ale vy sami musíte nejlépe vědět, že v životě není vždy jen to, co je snadné a zábavné…</p>",
    },
    {
      name: "Odevzdaní trpitelé",
      share: "Odhadujeme, že mezi lidmi, kterým již bylo 69 let, je takovýchto „trpitelů“ okolo 31 %, což z vás dělá „příslušníka“ největší skupiny v tomto věku.",
      desc:
        "<p>Rizika svého stárnutí vnímáte silně, ale intenzita vašeho jednání, které by mohlo těmto rizikům čelit, tomu neodpovídá. Stáří se bojíte, ale nic moc se svými obavami neděláte.</p><p>Snášení rizik stáří je pro vás alternativou k velmi pravděpodobným ztrátám, ke kterým by jinak došlo, kdybyste všechny zdroje nemohli použít na své dnešní nezbytné životní výdaje. Žít jen pro dnešní den je vaší životni strategie, a to i přes to, že výzvám stárnutí pravděpodobně už každý den čelíte. </p>",
      recom:
        "<p>To, že na rizika nereagujete, je dosti pravděpodobně důsledkem nedostatku zdrojů a sil k aktivnějšímu jednání. Fakt, že jste ve svém životě došel/došla až sem, je pozitivní signál. Přestože vy osobně zdroje (finanční, společenské nebo zdravotní) nemáte dostatečné, je možné v tomto případě jednat ve spolupráci s někým jiným: využít třeba pomoc rodiny či širšího sociálního okolí.</p><p>Péče o Vaše rodinné a společenské vazby je rozhodně i nyní prospěšnou investicí do budoucnosti – nejen do budoucnosti vaší, ale i té jejich.</p><p>Můžeme Vám také doporučit, abyste zvážili uspořádání přání týkajících se Vašeho majetku či zdraví. Lidé často tyto věci odkládají, ale jejich promyšlení a sepsání může pomoci vám i vašemu okolí. Víme, není to něco, co by člověk chtěl řešit, ale je to něco, co vám pomůže se tak trochu vymanit ze své (mírné?) odevzdanosti.</p>",
    },
    {
      name: "Bezstarostní jezdci",
      share: "Mezi bezstarostné jezdce jsme v našem výzkumu zařadili přibližně 29 % lidí, kterým bylo 70 let nebo více.",
      desc:
        "<p>Rizika stárnutí vnímáte méně intenzivně a stejně tak málo intenzivní a propracované jsou vaše strategie jednání ve vztahu k těmto možným rizikům. Když rizika nejsou, není s nimi, co dělat.</p><p>Zatímco mezi nejmladšími ročníky jsou „bezstarostní“ spíše ti, pro které je stáří vzdálenou budoucností, ve vaší věkové skupině už jde dost možná spíše o výraz optimistické a poklidné smířenosti s podzimem života.</p>",
      recom:
        "<p>Z výzkumů je známé, že zapojení do společenského života je výhodné z hlediska psychické pohody i jako forma zabezpečení. Ti, kdo mají více kontaktů a přátelských vazeb jsou na tom lépe.</p><p>Stejně tak je možné využít i dobře známé formy podpory zdraví – myslet na prevenci, informovat se a snažit se vyhýbat tomu, co zejména aktuální zdraví prokazatelně poškozuje.</p><p>Obecně je potřeba se zamyslet nad tím, zda nepotřebujete ve svém životě přeci jen něco zařídit. Míníme zde například některé z těch záležitostí, na které lidé neradi myslí, protože se týkají „posledních věcí v životě“, na které je ale radno myslet včas. Jedná se o sepsání závěti či vytvoření soupisu přání o léčbě na konci vašeho života. Věřte, že to pomůže i lidem kolem vás.</p><p>Možná si i vy sám/sama potřebujete v tomto smyslu utřídit svoje myšlenky. A nebojte se, řešení těchto věcí neznamená, že vás někdo odepisuje. Naopak, znamená to, že vás bere vážně.</p>",
    },
    {
      name: "Ostražití hlídači",
      share: "Ve vaší věkové skupině je přibližně 20 % ostražitých hlídačů, kteří se svým stářím aktivně pracují a nerezignovali na něj.",
      desc:
        "<p>Velmi silně vnímáte rizika stáří a zároveň se snažíte intenzivně a promyšleně na tato rizika připravovat, aby k jejich realizaci vůbec nedošlo nebo se co nejvíc oddálila a zmírnila. </p>",
      recom:
        "<p>Jde o aktivní přístup zaměřený na budoucnost, o přístup, který vychází z faktu, že i ve vyšším věku můžete aktivně jednat a ovlivňovat svůj život. Pocit, že člověk je tím, kdo má možnost o svém životě rozhodovat, je důležitý.</p><p>Některé faktory zdravého stárnutí jsou obecně známé: například vyvážená strava a přiměřený pohyb – sport, procházky v přírodě, ale jiné tak trochu unikají pozornosti, například přetrvávající pocit smyslu života, s tím spojená životní spokojenost a také fungující sociální kontakty. Vsaďte na mezigenerační vazby: komunikujte s mladšími generacemi. I když to možná není na první pohled patrné, vyplatí se tato komunikace nejen vám. Možná vám jejich osvěžující přístup k životu ulehčí  břímě životní ostražitosti.</p>",
    },
  ],
];

export default hodnoceni;
